# Dev workflow. Performs checks but does NOT release.

name: Dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read # To checkout.

jobs:
  check:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read # To publish a GitHub release.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
