# Release from main branch workflow.

name: Main branch check and release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write # To publish a GitHub release.
      issues: write # To comment on released issues.
      pull-requests: write # To comment on released pull requests.
      id-token: write # To enable use of OIDC for npm provenance.
