# Release workflow.

name: Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  check-and-build:
    uses: ./.github/workflows/checks.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: check-and-build
    permissions:
      contents: write # To publish a GitHub release.
      issues: write # To comment on released issues.
      pull-requests: write # To comment on released pull requests.
      id-token: write # To enable use of OIDC for npm provenance.
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
